### PR TITLE
Proposition to licence the code under the LGPL v3 licence

### PR DESCRIPTION
**Pull request by mdebony**
In the objective to better distribute the code it was some time ago proposed to add an open source licence. 
The purpose of this PR is to propose to add as licence the LGPLv3.
You could see the full licence in the LICENCE.txt file.

@MSCarrasco @gabemery @StFroese @aaguasca Please leave a comment to let me know if you agree or disagree with this licence. To proceed further the agreement of all the contributors is needed. 

In case this licence is rejected, I will look into a different one to propose.

### CODE REVIEW

**Comment by StFroese** [comment]
@mdebony what's reason for LGPL instead of GPL here? :)

**Comment by mdebony** [comment]
> @mdebony what's reason for LGPL instead of GPL here? :)

For me, this code is a library that could be used in connection with potentially quite a lot of different code. My understanding of the GPL is than the code using the library would have to become GPL also. I don't want to force people simply using the library to adopt a specific licence for their own code.

**Comment by StFroese** [comment]
> > @mdebony what's reason for LGPL instead of GPL here? :)
> 
> For me, this code is a library that could be used in connection with potentially quite a lot of different code. My understanding of the GPL is than the code using the library would have to become GPL also. I don't want to force people simply using the library to adopt a specific licence for their own code.

Ah ok I see, yes I thinks that's the case. 
For LGPL you allow that the library is linked to proprietary software. The software linking the library doesn't have to be LGPL but has to allow to exchange the linked code with any modifications of the library. 
For GPL you are forced that your code where you want to link the library has to be free and open source

**Comment by gabemery** [comment]
I agree to this licence

**Comment by MSCarrasco** [comment]
I also agree to this licence

**Comment by aaguasca** [comment]
I also agree to this licence

**Comment by mdebony** [comment]
Thanks everyone. The PR is now merged to apply the licence to the code.

**Pull request merged**
